config/routes.rb
Rails.application.routes.draw do
  get 'moviedb/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # I changed it from double nested resources below:
  # resources :movies do
  #   resources :reviews do
  #     resources :votes
  #   end
  # end

  resources :movies do
    resources :reviews
  end

  resources :reviews do
    resources :votes
  end

  resources :reviews do
    member do
      post 'upvote'
    end
  end

  resources :reviews do
    resources :comments
  end

  resources :votes

  resources :genres

  resources :api

  # get 'movies/search'

  resources :users

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'
  #This is movie index page

  root "movies#welcome"

  # root 'movie#index'

end

app/controllers/movies_controller.rb
require 'themoviedb'
class MoviesController < ApplicationController
  def welcome
    @movies = Movie.all
    @movie = Movie.new
    @genres = Genre.all
    @result = Tmdb::Movie.find("Batman")

    # @search = Tmdb::Search.new
    # @search.resource('movie')
    # @search.query(@movie)
    # @result = @search.fetch

  end


  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movie_path(@movie)
    else
      render :new
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def destroy
    @movie = Movie.find(params[:id])

    @movie.destroy
    redirect_to movies_path
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :year, :director)
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_search.html.erb
<form id='moviesearch' method='post' action='/api'>
  <label>Movie Title</label>
  <input id='movietitle' type='text' name='movie' value='movie' placeholder='title' >
  <input name="search" type="submit" />
</form>

app/views/movies/index.html.erb
<h1>All Movies by Title</h1>
<ul>
<% @movies.each do |movie| %>
  <li> <%= link_to movie.title, movie_path(movie) %> (<%= movie.reviews.length %> reviews) </li>
<% end %>
</ul>

app/views/movies/new.html.erb
<div>
<%= form_for @movie, url: {action: "create"} do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </p>
  <p>
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </p>
  <p>
    <%= f.label :mpaa_rating, "MPAA Rating" %><br>
    <%= f.text_field :mpaa_rating %>
  </p>
  <p>
    <%= f.label :genre %><br>
    <%= f.collection_select :genres, Genre.all, :id, :name, prompt: true %>
  </p>
  <p>
    <%= f.submit "Create New Movie"%><br>
  </p>
<% end %>
</div>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>
<h3>Overall rating: </h3>
  <!-- some class method call to determine rating -->
<h3>Movie details</h3>
<ul>
<li>Release year: <%= @movie.year %></li>
<li>Director: <%= @movie.director %></li>
<!-- MPAA ratings usually missing for older movies -->
<li>MPAA rating:
<% if @movie.mpaa_rating != nil %>
  <%= @movie.mpaa_rating %>
<% else %>
  <p>No rating available</p>
<%end %></li>



<!-- ooh maybe the number of reviews -->
<h3>Reviews</h3>
<% if @movie.reviews.length > 0 %>
<!-- if reviews exist, display -->
  <% @movie.reviews.each do |review| %>
  <div class="review">
    <p>Rating: <%= review.star_rating %>
    <p>Reviewer: <%= review.user.username %></p>
    <p><%= review.text %></p>

    <!-- I changed the path from movie_review_votes_path to review_votes_path -->
    <p>Was this review helpful? </p>


    <!-- from http://docs.railsbridge.org/intro-to-rails/allow_people_to_vote -->
    <%= pluralize(review.votes.count, "vote") %>
    <%= button_to 'upvote', upvote_review_path(review), method: :post %>

    <!-- comments -->
    <% if review.comments.length > 0 %>
    <h4>Comments</h4>
    <% review.comments.each do |comment| %>
      <div class="comment">
      <p>
        <%= comment.text%><br />
        <%= comment.user.username %>
      </p>
      </div>
    <% end %>
    <% end %>

      <%= link_to "Add a Comment", new_review_comment_path(review.id) %>


  </div>
  <hr>
  <% end %>
<!-- else, suggest they add a review -->
<% else %>
  <p>This movie hasn't been reviewed yet.</p>
  <!-- debug path later -->


<% end %>

<%= link_to "Create New Review", new_movie_review_path(@movie) %>

app/views/movies/welcome.html.erb
<h1>Cinemagic</h1>
<p>A reviews site for the discerning movie-goer.</p>

<!-- Admin only -->
<% if user_signed_in? %>
  <h2>Contribute</h2>
  <p>Help us make the Cinemagic community better:</p>
  <ul>
    <li><%= link_to "Add a movie to the collection", new_movie_path %></li>
    <li><%= link_to "Add a review", movies_path %></li>
    <li><%= link_to "Vote on user reviews", movies_path %></li>
  </ul>
<% end %>

<h2>Latest Reviews</h2>
<ul>
<% @movies.each do |movie| %>
  <li> <%= link_to movie.title, movie_path(movie) %> (<%= movie.reviews.length %> reviews) </li>
<% end %>
</ul>
<button class="btn btn-secondary btn-lg"><%= link_to "All Movies", movies_path %></button>

<div id='searcharea'>
  <h1>Movie Search</h1>
  <div id="search_movie">
    <%= render 'movies/search', movie: @movie %>
  </div>
  <!-- <section id="fetch">
      <input type="text" placeholder="Enter a movie title" id="term" width="40" />
      <button id="search">Search</button>
  </section> -->

<div id='space'></div>
<div id="Answer Container">
  <section id="poster"></section>
</div>

</div>

<h2><%= link_to "Browse by Genre", genres_path %></h2>
<!-- eventually limit the number of genres displayed on homepage? -->
<div class="card-columns">
<% @genres.each do |genre| %>
  <div class="card text-xs-center">
    <div class="card-block">
      <h3 class="card-title"><%= link_to genre.name.titlecase, genre_path(genre) %></h3>
      <%= image_tag "film.png" %>
    </div>
  </div>
<% end %>
</div>

<!-- alerts and notices -->
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>